"use client";
import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { RoadmapResponse } from "@/types";

interface Props {
  roadmap: RoadmapResponse;
  profileName?: string;
}

export default function ExportPDF({ roadmap, profileName }: Props) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    try {
      const jsPDF = (await import("jspdf")).default;

      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageW   = 210;
      const pageH   = 297;
      const margin  = 18;
      const cw      = pageW - margin * 2;
      const today   = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

      // ─── Brand colours ────────────────────────────────────────────────────────
      const DARK_GREEN  : [number,number,number] = [0, 77, 64];
      const MID_GREEN   : [number,number,number] = [0, 105, 92];
      const ACCENT      : [number,number,number] = [0, 191, 165];
      const SLATE       : [number,number,number] = [71, 85, 105];
      const LIGHT_BG    : [number,number,number] = [248, 250, 252];
      const BORDER      : [number,number,number] = [226, 232, 240];
      const RED         : [number,number,number] = [220, 38, 38];
      const AMBER       : [number,number,number] = [217, 119, 6];
      const GREEN_RISK  : [number,number,number] = [22, 163, 74];
      const BLACK       : [number,number,number] = [15, 23, 42];
      const WHITE       : [number,number,number] = [255, 255, 255];

      const riskCol = (r: string): [number,number,number] =>
        r === "Low" ? GREEN_RISK : r === "Medium" ? AMBER : RED;

      // helper: draw filled rounded rect (jsPDF doesn't expose typed overloads cleanly)
      const fillRect = (x:number, y:number, w:number, h:number, fill:[number,number,number], stroke?:[number,number,number], radius=2) => {
        pdf.setFillColor(...fill);
        if (stroke) { pdf.setDrawColor(...stroke); pdf.roundedRect(x, y, w, h, radius, radius, "FD"); }
        else { pdf.roundedRect(x, y, w, h, radius, radius, "F"); }
      };

      // helper: add page if not enough space
      let curY = 0;
      const ensureSpace = (needed: number) => {
        if (curY + needed > pageH - 20) { pdf.addPage(); curY = 20; }
      };

      // ─── PAGE 1: Cover ────────────────────────────────────────────────────────
      // Full-page dark header
      fillRect(0, 0, pageW, 70, DARK_GREEN);

      // Logo placeholder bar
      pdf.setFillColor(...ACCENT);
      pdf.rect(0, 0, 6, 70, "F");

      // Company name
      pdf.setTextColor(...WHITE);
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "bold");
      pdf.text("SANATAN LABS", margin, 14);
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(7.5);
      pdf.text("PASSIONIT-PRUTL · KALKI AI DHARMA FRAMEWORK", margin, 20);

      // Horizontal rule
      pdf.setDrawColor(...ACCENT);
      pdf.setLineWidth(0.4);
      pdf.line(margin, 23, pageW - margin, 23);

      // Document title
      pdf.setFontSize(20);
      pdf.setFont("helvetica", "bold");
      pdf.text("Career Transition Roadmap", margin, 36);

      // Candidate info
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(200, 240, 235);
      pdf.text(`Prepared for: ${profileName || "Candidate"}`, margin, 47);
      pdf.setFontSize(9);
      pdf.text(`Report Date: ${today}  ·  Confidential`, margin, 54);
      pdf.text(`Generated by Sanatan Labs KALKI AI Engine`, margin, 60);

      // ─── Summary card ─────────────────────────────────────────────────────────
      curY = 80;
      fillRect(margin, curY, cw, 44, LIGHT_BG, BORDER);

      pdf.setTextColor(...DARK_GREEN);
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.text("Transition Summary", margin + 5, curY + 10);

      pdf.setFontSize(11);
      pdf.setTextColor(...BLACK);
      pdf.text(`${roadmap.current_role}  →  ${roadmap.target_role}`, margin + 5, curY + 19);

      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(...SLATE);

      const probColor = roadmap.success_probability >= 70 ? GREEN_RISK : roadmap.success_probability >= 50 ? AMBER : RED;
      pdf.setTextColor(...probColor);
      pdf.setFont("helvetica", "bold");
      pdf.text(`${roadmap.success_probability}% Success Probability`, margin + 5, curY + 27);

      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(...SLATE);
      pdf.text(`Total Timeline: ${roadmap.total_transition_months} months  ·  ${roadmap.roadmap_nodes.length} transition steps`, margin + 5, curY + 34);

      curY += 52;

      // ─── Explanation ──────────────────────────────────────────────────────────
      pdf.setTextColor(...DARK_GREEN);
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      pdf.text("AI Assessment", margin, curY);
      curY += 6;

      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(9.5);
      pdf.setTextColor(...SLATE);
      const expLines = pdf.splitTextToSize(roadmap.explanation || "Assessment not available.", cw);
      pdf.text(expLines, margin, curY);
      curY += expLines.length * 5 + 10;

      // ─── Roadmap steps ────────────────────────────────────────────────────────
      pdf.setDrawColor(...BORDER);
      pdf.setLineWidth(0.3);
      pdf.line(margin, curY, pageW - margin, curY);
      curY += 8;

      pdf.setTextColor(...DARK_GREEN);
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.text("Career Transition Steps", margin, curY);
      curY += 10;

      for (const node of roadmap.roadmap_nodes) {
        const boxH = node.skill_gap?.length > 0 ? 42 : 36;
        ensureSpace(boxH + 6);

        const rc = riskCol(node.risk_level);
        fillRect(margin, curY, cw, boxH, LIGHT_BG, rc, 3);

        // Step badge
        pdf.setFillColor(...rc);
        pdf.roundedRect(margin + 4, curY + 4, 18, 7, 2, 2, "F");
        pdf.setTextColor(...WHITE);
        pdf.setFontSize(7);
        pdf.setFont("helvetica", "bold");
        pdf.text(`STEP ${node.node_order}`, margin + 5.5, curY + 9);

        // Role title
        pdf.setTextColor(...BLACK);
        pdf.setFontSize(11);
        pdf.setFont("helvetica", "bold");
        pdf.text(node.role_title, margin + 26, curY + 9);

        // Meta row
        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(8.5);
        pdf.setTextColor(...SLATE);
        const metaParts = [
          node.timeline_months > 0 ? `+${node.timeline_months} months` : "Now",
          `₹${node.salary_estimate_lpa} LPA`,
          `${node.risk_level} Risk`,
        ];
        pdf.text(metaParts.join("   ·   "), margin + 5, curY + 18);

        // Description
        const descLines = pdf.splitTextToSize(node.description || "", cw - 10);
        pdf.text(descLines.slice(0, 2), margin + 5, curY + 25);

        // Skill gaps
        if (node.skill_gap?.length > 0) {
          pdf.setTextColor(...RED);
          pdf.setFont("helvetica", "bold");
          pdf.setFontSize(8);
          pdf.text("Build: ", margin + 5, curY + 36);
          pdf.setFont("helvetica", "normal");
          pdf.text(node.skill_gap.slice(0, 5).join(" · "), margin + 15, curY + 36);
        }

        curY += boxH + 5;
      }

      // ─── Alternative paths ────────────────────────────────────────────────────
      if (roadmap.alternative_paths?.length > 0) {
        ensureSpace(40);
        pdf.setDrawColor(...BORDER);
        pdf.line(margin, curY, pageW - margin, curY);
        curY += 8;

        pdf.setTextColor(...DARK_GREEN);
        pdf.setFontSize(12);
        pdf.setFont("helvetica", "bold");
        pdf.text("Alternative Career Paths", margin, curY);
        curY += 8;

        for (const alt of roadmap.alternative_paths) {
          ensureSpace(20);
          fillRect(margin, curY, cw, 18, LIGHT_BG, BORDER, 2);
          pdf.setTextColor(...MID_GREEN);
          pdf.setFontSize(9.5);
          pdf.setFont("helvetica", "bold");
          pdf.text(alt.path_name, margin + 4, curY + 7);
          pdf.setFont("helvetica", "normal");
          pdf.setTextColor(...SLATE);
          pdf.setFontSize(8.5);
          pdf.text(`${alt.success_probability}% probability  ·  ${alt.total_months} months`, margin + 4, curY + 13);
          curY += 22;
        }
      }

      // ─── Audit scores (full page) ─────────────────────────────────────────────
      if (roadmap.audit_scores?.length > 0) {
        pdf.addPage();
        curY = 20;

        fillRect(0, 0, pageW, 22, DARK_GREEN);
        pdf.setFillColor(...ACCENT);
        pdf.rect(0, 0, 6, 22, "F");
        pdf.setTextColor(...WHITE);
        pdf.setFontSize(13);
        pdf.setFont("helvetica", "bold");
        pdf.text("Ethical AI Audit — PASSIONIT + PRUTL", margin, 14);
        curY = 30;

        // Framework legend
        fillRect(margin, curY, cw / 2 - 3, 14, [237, 246, 243], [0, 105, 92], 2);
        fillRect(margin + cw / 2 + 3, curY, cw / 2 - 3, 14, [240, 253, 250], [0, 191, 165], 2);
        pdf.setTextColor(...DARK_GREEN);
        pdf.setFontSize(8);
        pdf.setFont("helvetica", "bold");
        pdf.text("PASSIONIT (9 dimensions)", margin + 4, curY + 6);
        pdf.text("Purpose · Accountability · Safety · Sustainability · Inclusivity", margin + 4, curY + 11);
        pdf.setTextColor(...[0, 105, 92] as [number,number,number]);
        pdf.text("PRUTL (5 dimensions)", margin + cw / 2 + 7, curY + 6);
        pdf.text("Privacy · Reliability · Usability · Trustworthiness · Legality", margin + cw / 2 + 7, curY + 11);
        curY += 22;

        for (const score of roadmap.audit_scores) {
          ensureSpace(22);
          const sc = riskCol(score.risk_level);

          // Left accent
          pdf.setFillColor(...sc);
          pdf.rect(margin, curY, 3, 18, "F");

          fillRect(margin + 3, curY, cw - 3, 18, LIGHT_BG, BORDER, 2);

          // Dimension + framework
          pdf.setTextColor(...BLACK);
          pdf.setFontSize(9.5);
          pdf.setFont("helvetica", "bold");
          pdf.text(`${score.dimension}`, margin + 8, curY + 7);

          pdf.setFontSize(7.5);
          pdf.setTextColor(...SLATE);
          pdf.setFont("helvetica", "normal");
          pdf.text(score.framework, margin + 8, curY + 12);

          // Score badge
          pdf.setFillColor(...sc);
          pdf.roundedRect(pageW - margin - 24, curY + 3, 18, 12, 2, 2, "F");
          pdf.setTextColor(...WHITE);
          pdf.setFontSize(10);
          pdf.setFont("helvetica", "bold");
          pdf.text(`${score.score}/10`, pageW - margin - 22, curY + 11);

          // Risk label
          pdf.setTextColor(...sc);
          pdf.setFontSize(7.5);
          pdf.setFont("helvetica", "bold");
          pdf.text(score.risk_level, pageW - margin - 32, curY + 7);

          // Explanation (truncated to 1 line)
          pdf.setTextColor(...SLATE);
          pdf.setFont("helvetica", "normal");
          pdf.setFontSize(7.5);
          const expShort = pdf.splitTextToSize(score.explanation || "", cw - 55);
          pdf.text(expShort.slice(0, 1), margin + 8, curY + 17);

          curY += 22;
        }
      }

      // ─── Emotional forecast ───────────────────────────────────────────────────
      if (roadmap.emotional_forecast?.length > 0) {
        ensureSpace(60);
        pdf.setDrawColor(...BORDER);
        pdf.line(margin, curY, pageW - margin, curY);
        curY += 8;

        pdf.setTextColor(...DARK_GREEN);
        pdf.setFontSize(12);
        pdf.setFont("helvetica", "bold");
        pdf.text("Journey Forecast", margin, curY);
        curY += 8;

        for (const phase of roadmap.emotional_forecast) {
          ensureSpace(20);
          const sc = phase.stress_level === "High" ? RED : phase.stress_level === "Medium" ? AMBER : GREEN_RISK;
          pdf.setFillColor(...sc);
          pdf.circle(margin + 3, curY + 5, 2, "F");
          pdf.setTextColor(...BLACK);
          pdf.setFontSize(9);
          pdf.setFont("helvetica", "bold");
          pdf.text(`${phase.timeline}  ·  ${phase.phase}`, margin + 8, curY + 6);
          pdf.setFont("helvetica", "normal");
          pdf.setFontSize(8.5);
          pdf.setTextColor(...SLATE);
          const dLines = pdf.splitTextToSize(phase.description || "", cw - 10);
          pdf.text(dLines.slice(0, 2), margin + 8, curY + 12);
          curY += 20;
        }
      }

      // ─── Footer on every page ─────────────────────────────────────────────────
      const totalPages = (pdf as any).internal.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);

        // Footer bar
        pdf.setFillColor(...DARK_GREEN);
        pdf.rect(0, pageH - 12, pageW, 12, "F");
        pdf.setFillColor(...ACCENT);
        pdf.rect(0, pageH - 12, 6, 12, "F");

        pdf.setTextColor(...WHITE);
        pdf.setFontSize(7);
        pdf.setFont("helvetica", "normal");
        pdf.text("SANATAN LABS — PASSIONIT-PRUTL KALKI AI DHARMA Framework  ·  Confidential", margin, pageH - 5);
        pdf.text(`Page ${i} of ${totalPages}`, pageW - margin - 18, pageH - 5);
      }

      const safeName = (profileName || "candidate").replace(/\s+/g, "-").toLowerCase();
      const safeRole = (roadmap.target_role || "roadmap").replace(/\s+/g, "-").toLowerCase();
      pdf.save(`sanatan-labs-${safeName}-${safeRole}.pdf`);
    } catch (err) {
      console.error("PDF export failed:", err);
    } finally {
      setExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="flex items-center gap-1.5 text-xs text-white/70 hover:text-white bg-white/10 hover:bg-white/20 px-3 py-1.5 rounded-lg transition-colors disabled:opacity-50"
    >
      {exporting
        ? <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Exporting...</>
        : <><Download className="w-3.5 h-3.5" /> Export PDF</>
      }
    </button>
  );
}
