"""
rag/roadmap_builder.py — Data-driven roadmap builder.

Uses the career knowledge graph (NetworkX) + neural scorer (sentence-transformers)
to build personalized roadmap nodes from our knowledge base.

No fixed taxonomy. Any career goal works. The graph learned from our KB.
Groq writes ONE explanation paragraph only.
"""

from __future__ import annotations
import math
from rag.embedder import get_model, get_collection
from rag.neural_scorer import (
    classify_domain,
    semantic_skill_gap,
    neural_probability,
    DOMAIN_DESCRIPTIONS,
)
from rag.knowledge_graph import build_career_graph, find_career_path


# ─── Salary ranges from career_clusters (Indian market, LPA) ─────────────────
# Ordered: [entry, mid, senior, lead]
SALARY_RANGES = {
    # Keys match KB_DOMAIN_MAP normalised names
    "ai & ml":            [8,  16, 28, 45],
    "data analytics":     [5,  10, 18, 30],
    "full stack":         [6,  14, 24, 38],
    "cloud & devops":     [7,  14, 24, 40],
    "cybersecurity":      [7,  14, 22, 38],
    "product management": [10, 18, 30, 50],
    "ui/ux":              [5,  10, 18, 28],
    "fintech":            [8,  16, 28, 45],
    "edtech":             [5,  10, 16, 28],
    "healthcare it":      [6,  12, 20, 32],
    "embedded & iot":     [6,  12, 20, 35],
    "gaming":             [5,  11, 20, 32],
    "research":           [6,  12, 20, 35],
    "consulting":         [8,  14, 24, 40],
    "entrepreneurship":   [4,  12, 20, 35],
    "global delivery":    [10, 18, 28, 45],
    "hr technology":      [5,  10, 16, 26],
    "finance":            [8,  15, 25, 42],
    "sales":              [5,  12, 20, 35],
    "digital marketing":  [4,   8, 15, 25],
    "legal tech":         [6,  12, 20, 35],
    "supply chain":       [6,  12, 20, 35],
    "content":            [3,   7, 14, 25],
    "sustainability":     [5,  10, 18, 30],
    "civil engineering":  [5,  10, 18, 32],
}

# Timeline per seniority transition (months)
SENIORITY_TIMELINE = {
    (0, 1): 6,   (0, 2): 10, (0, 3): 14,
    (1, 2): 8,   (1, 3): 12, (1, 4): 18,
    (2, 3): 10,  (2, 4): 15, (2, 5): 20,
    (3, 4): 12,  (3, 5): 18, (3, 6): 24,
    (4, 5): 14,  (4, 6): 20,
    (5, 6): 16,
}


def _get_salary(domain: str, seniority: int) -> float:
    ranges = SALARY_RANGES.get(domain, [6, 12, 22, 36])
    idx = min(seniority // 2, len(ranges) - 1)
    return float(ranges[idx])


def _timeline_between(s1: int, s2: int) -> int:
    key = (min(s1, s2), max(s1, s2))
    return SENIORITY_TIMELINE.get(key, abs(s2 - s1) * 8)


def _groq_classify_domain(profile: dict) -> tuple[str | None, bool]:
    """
    Two-step Groq domain classifier:

    Step A — Ask Groq: "Is this career goal in our 25-domain taxonomy?"
      - If YES → return (domain_name, False)   means: use system knowledge graph
      - If NO  → return (None, True)            means: build custom roadmap with Groq

    This means 'psychologist', 'chef', 'lawyer', 'architect' etc. get a REAL
    custom path generated by Groq — not forced into the wrong box.

    Returns (domain: str | None, is_custom: bool)
    """
    goal    = (profile.get("career_goal") or "").strip()
    current = (profile.get("current_role") or "").strip()
    domains = (profile.get("interest_domains") or [])

    if not goal and not current:
        return None, False

    domain_list = ", ".join(DOMAIN_DESCRIPTIONS.keys())
    context = f'Career goal: "{goal}"'
    if current:
        context += f' | Current role: "{current}"'

    prompt = (
        f"{context}\n\n"
        f"Our system knows these 25 career domains:\n{domain_list}\n\n"
        f"Does this person's career goal fit well into one of the 25 domains above?\n"
        f"- If YES, reply: DOMAIN: <exact domain name from the list>\n"
        f"- If NO (e.g. psychologist, chef, architect, pilot, nurse, lawyer, teacher not in edtech), "
        f"reply: CUSTOM\n\n"
        f"Important rules:\n"
        f"- 'full stack developer', 'web developer', 'backend engineer' → DOMAIN: full stack\n"
        f"- 'leadership in full stack' → DOMAIN: full stack (leadership qualifier, same field)\n"
        f"- 'data analyst', 'business analyst' → DOMAIN: data analytics\n"
        f"- 'psychologist', 'therapist', 'counselor' → CUSTOM\n"
        f"- 'chef', 'restaurant owner' → CUSTOM\n"
        f"- 'architect (buildings)' → CUSTOM\n"
        f"- 'doctor', 'surgeon' → CUSTOM\n"
        f"Reply with ONLY 'DOMAIN: <name>' or 'CUSTOM'. Nothing else."
    )

    try:
        from groq import Groq
        from config import get_settings
        settings = get_settings()
        client = Groq(api_key=settings.groq_api_key)
        response = client.chat.completions.create(
            model=settings.groq_model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            max_tokens=20,
        )
        raw = response.choices[0].message.content.strip().lower()

        if raw.startswith("domain:"):
            extracted = raw.replace("domain:", "").strip().strip('"').strip("'")
            for domain in DOMAIN_DESCRIPTIONS.keys():
                if domain == extracted or domain in extracted or extracted in domain:
                    print(f"  Groq domain: '{domain}' (in-taxonomy)")
                    return domain, False

        if "custom" in raw:
            print(f"  Groq: goal is OUTSIDE taxonomy → will build custom roadmap")
            return None, True

    except Exception as e:
        print(f"  Groq domain classification failed ({e}) — falling back to neural")

    return None, False


def _groq_build_custom_roadmap(profile: dict, prob_min: int, prob_max: int) -> dict | None:
    """
    When the career goal is outside our 25 domains (psychologist, chef, architect etc.),
    Groq generates the FULL structured roadmap directly — real role titles, real skills,
    real Indian market salaries, realistic timelines.

    No taxonomy constraints. No knowledge graph forcing. Pure intelligence.
    """
    goal         = (profile.get("career_goal") or "").strip()
    current      = (profile.get("current_role") or "Student").strip()
    skills       = profile.get("technical_skills") or []
    soft_skills  = profile.get("soft_skills") or []
    years_exp    = profile.get("years_of_experience") or 0
    burnout      = profile.get("burnout_level") or 5
    employment   = profile.get("employment_status") or ""
    is_student   = employment == "Student"

    context = (
        f"Person: {current}, {years_exp} years experience.\n"
        f"Technical skills: {', '.join(skills[:6]) or 'none listed'}.\n"
        f"Soft skills: {', '.join(soft_skills[:3]) or 'none'}.\n"
        f"Career goal: {goal}.\n"
        f"{'Student — building first career path.' if is_student else ''}"
        f"Burnout: {burnout}/10."
    )

    prompt = (
        f"Build a career roadmap for this person.\n{context}\n\n"
        f"Return ONLY valid JSON (no markdown) with this exact structure:\n"
        f'{{"target_role": "string",'
        f'"total_transition_months": number,'
        f'"success_probability": number (between {prob_min} and {prob_max}),'
        f'"roadmap_nodes": ['
        f'  {{"node_id": "node_1", "role_title": "string", "node_order": 1, '
        f'"timeline_months": 0, "required_skills": ["skill1","skill2"], '
        f'"skill_gap": [], "salary_estimate_lpa": number, "risk_level": "Low", '
        f'"description": "string (2 sentences, second person, specific)"}},'
        f'  ... 3 more nodes with node_order 2,3,4 ...'
        f'],'
        f'"roadmap_edges": [{{"source":"node_1","target":"node_2","label":"string"}}, ...],'
        f'"alternative_paths": ['
        f'  {{"path_name":"string","roles":["r1","r2"],"total_months":number,"success_probability":number}}'
        f'],'
        f'"emotional_forecast": ['
        f'  {{"phase":"string","timeline":"string","stress_level":"Medium","description":"string"}}'
        f']}}\n\n'
        f"Rules:\n"
        f"- Use real Indian market salaries (LPA). Entry ₹3-8, mid ₹8-20, senior ₹20-40+.\n"
        f"- role_title must be the ACTUAL profession (e.g. 'Clinical Psychologist', not 'Research Professional')\n"
        f"- skill_gap = skills the person doesn't have yet but need\n"
        f"- Timelines realistic: entry cert 6-12mo, full transition 18-36mo for career changes\n"
        f"- description: user-friendly, second person, specific (not 'Target milestone: ...')\n"
        f"- 4 nodes, 3 edges, 2 alternative paths, 3 emotional phases\n"
        f"- Return ONLY JSON, no explanation."
    )

    try:
        from groq import Groq
        from config import get_settings
        import json, re
        settings = get_settings()
        client = Groq(api_key=settings.groq_api_key)
        response = client.chat.completions.create(
            model=settings.groq_model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=2000,
            response_format={"type": "json_object"},
        )
        raw = response.choices[0].message.content
        data = json.loads(raw)
        print(f"  Groq custom roadmap built: {data.get('target_role')} in {data.get('total_transition_months')}mo")
        return data
    except Exception as e:
        print(f"  Groq custom roadmap failed: {e}")
        return None


def _build_profile_query(profile: dict) -> str:
    """Build a rich text query for neural domain classification."""
    parts = [
        profile.get("career_goal", ""),
        " ".join(profile.get("interest_domains", [])),
        profile.get("current_role", ""),
        profile.get("current_industry", ""),
        " ".join(profile.get("technical_skills", [])[:5]),
        # Include soft skills + certifications for richer domain signal
        " ".join(profile.get("soft_skills", [])[:3]),
        " ".join(profile.get("certifications", [])[:3]),
    ]
    return " ".join(p for p in parts if p).strip()


def build_roadmap_from_data(
    profile:      dict,
    retrieved_docs: list[dict],
    prob_min:     int,
    prob_max:     int,
) -> dict:
    """
    Build complete roadmap structure using:
    1. Neural domain classifier → identifies target domain from any free text
    2. Career knowledge graph → finds real transition path from KB
    3. Semantic skill gap → embedding-based skill comparison, no string matching
    4. Neural probability → MLP on transformer features
    5. Groq explanation → ONE call, fills the explanation field after return

    Returns same schema as before — frontend unchanged.
    """
    current_role       = profile.get("current_role", "")
    employment_status  = profile.get("employment_status", "")
    is_student         = employment_status == "Student"
    user_skills        = profile.get("technical_skills", [])
    soft_skills        = profile.get("soft_skills", [])
    certifications     = profile.get("certifications", [])
    burnout            = profile.get("burnout_level", 5)
    years_exp          = profile.get("years_of_experience", 0)
    willing_relocate   = profile.get("willing_to_relocate", False)
    work_style         = profile.get("preferred_work_style", "Hybrid")
    target_timeline    = profile.get("target_timeline_years", 2)

    # Merge certifications as extra skills for gap computation
    if certifications:
        user_skills = list(dict.fromkeys(user_skills + certifications))

    # ── Step 1: Groq domain check — in taxonomy or custom path? ─────────────
    # Groq reads the actual career goal first.
    # If it's within our 25 domains (full stack, AI/ML, etc.) → system builds path.
    # If it's OUTSIDE (psychologist, chef, architect) → Groq builds the ENTIRE roadmap.
    # No forced mapping. No wrong domain. No taxonomy ceiling.
    query_text = _build_profile_query(profile)
    groq_domain, is_custom = _groq_classify_domain(profile)

    # ── CUSTOM PATH: goal outside our 25 domains ─────────────────────────────
    if is_custom:
        custom = _groq_build_custom_roadmap(profile, prob_min, prob_max)
        if custom:
            # Merge explanation placeholder and return directly
            custom.setdefault("current_role", current_role or "Starting Point")
            custom.setdefault("explanation", "")
            custom.setdefault("retrieved_doc_ids", [])
            # Ensure all nodes have required fields
            for node in custom.get("roadmap_nodes", []):
                node.setdefault("skill_gap", [])
                node.setdefault("required_skills", [])
                node.setdefault("description", f"Step toward {custom['target_role']}.")
                node.setdefault("risk_level", "Medium")
                node.setdefault("salary_estimate_lpa", 8.0)
            return custom
        # Groq failed — fall through to system with neural classifier

    # ── IN-TAXONOMY PATH: use system knowledge graph ──────────────────────────
    if groq_domain:
        target_domain = groq_domain
        domain_conf   = 0.95
        domain_scores = [(target_domain, 0.95)] + [
            (d, s) for d, s in classify_domain(query_text, top_k=4)
            if d != target_domain
        ][:3]
        print(f"Groq domain: {target_domain}")
    else:
        domain_scores = classify_domain(query_text, top_k=3)
        target_domain = domain_scores[0][0]
        domain_conf   = domain_scores[0][1]
        print(f"Neural domain: {target_domain} ({round(domain_conf*100)}%)")

    # ── Step 2: Knowledge graph path finding ──────────────────────────────────
    graph_path = find_career_path(current_role, target_domain, max_steps=4)
    print(f"Graph path: {[n['role_title'] for n in graph_path]}")

    # ── Step 3: Fetch KB docs for skill enrichment ────────────────────────────
    try:
        collection = get_collection()
        kb_results = collection.query(
            query_texts=[f"{target_domain} skills requirements career"],
            n_results=min(8, collection.count()),
        )
        kb_skill_texts = " ".join(kb_results["documents"][0]) if kb_results["documents"] else ""
    except Exception:
        kb_skill_texts = ""

    # ── Step 4: Build nodes ───────────────────────────────────────────────────
    nodes   = []
    cumulative_months = 0
    domain_desc = DOMAIN_DESCRIPTIONS.get(target_domain, f"{target_domain} professional")

    # Node 1 — current position (always first, no skill gap)
    if is_student:
        node1_title = current_role or "Student"
        node1_desc  = (
            f"You're starting your career journey"
            f"{f' studying {current_role}' if current_role else ''}. "
            f"{'You have ' + str(len(user_skills)) + ' technical skills already — ' + ', '.join(user_skills[:3]) + ' — which gives you a real head start. ' if user_skills else 'Use this phase to build your foundational skills. '}"
            f"The roadmap below shows exactly what you need to land your first role in {target_domain}."
        )
        node1_salary = 0.0
    else:
        node1_title = current_role or "Current Role"
        node1_desc  = (
            f"Your starting point. "
            f"{'You bring ' + str(len(user_skills)) + ' technical skills (' + ', '.join(user_skills[:3]) + ('...' if len(user_skills) > 3 else '') + ') into this transition. ' if user_skills else ''}"
            f"{'Willing to relocate — this opens more opportunities. ' if willing_relocate else ''}"
            f"Preferred working style: {work_style}."
        )
        node1_salary = float(profile.get("current_salary_lpa", 0) or _get_salary(target_domain, 1))

    nodes.append({
        "node_id":             "node_1",
        "role_title":          node1_title,
        "node_order":          1,
        "timeline_months":     0,
        "required_skills":     user_skills[:6],
        "skill_gap":           [],
        "salary_estimate_lpa": node1_salary,
        "risk_level":          "Low",
        "description":         node1_desc,
    })

    # Graph-derived intermediate nodes
    path_to_use = graph_path if graph_path else []

    # Skip node if it matches current role
    path_to_use = [n for n in path_to_use if n["role_title"].lower() != current_role.lower()]

    for i, path_node in enumerate(path_to_use[:3]):
        role_title = path_node["role_title"]
        seniority  = path_node.get("seniority", i + 2)

        # Required skills: graph node skills + KB-extracted skills
        graph_skills   = path_node.get("skills", [])
        required_skills = list(dict.fromkeys(graph_skills))[:8]  # deduplicate

        # Semantic skill gap using embeddings
        _, skill_gap, overlap_ratio = semantic_skill_gap(
            user_skills, required_skills, threshold=0.60
        )

        # Timeline from seniority progression
        prev_seniority = nodes[-1].get("_seniority", 1) if nodes else 1
        stage_months   = _timeline_between(prev_seniority, seniority)

        # Students and people starting fresh need minimum ramp-up time
        if is_student or years_exp == 0:
            stage_months = max(stage_months, 4 + i * 2)  # at least 4, 6, 8 months per step
        elif stage_months == 0:
            stage_months = 6  # never 0 months between steps

        if burnout >= 7:
            stage_months = round(stage_months * 1.3)
        elif burnout <= 3 and years_exp > 3:
            stage_months = round(stage_months * 0.85)
        cumulative_months += stage_months

        # Salary from domain + seniority
        salary = _get_salary(target_domain, seniority)

        # Risk from skill gap ratio
        gap_ratio  = 1 - overlap_ratio
        risk_level = "High" if gap_ratio > 0.65 else ("Medium" if gap_ratio > 0.35 else "Low")

        # User-friendly description
        overlap_pct = round(overlap_ratio * 100)
        n_gaps      = len(skill_gap)
        top_gaps    = skill_gap[:2]

        if i == 0:
            if is_student:
                desc = (
                    f"Your first career milestone: {role_title}. "
                    f"{'You already have ' + str(overlap_pct) + '% of the skills needed — great head start. ' if overlap_pct > 0 else ''}"
                    f"{'Build ' + ' and '.join(top_gaps) + ' to get here. ' if top_gaps else ''}"
                    f"Focus on projects and internships during this phase."
                )
            else:
                desc = (
                    f"First milestone: {role_title}. "
                    f"You're {overlap_pct}% of the way there on skills already. "
                    f"{'Main gaps to close: ' + ', '.join(top_gaps) + '. ' if top_gaps else 'You have strong coverage here. '}"
                    f"Estimated ₹{salary} LPA once you make this transition."
                )
        elif i == len(path_to_use[:3]) - 1:
            desc = (
                f"Your target role: {role_title}. "
                f"By this stage you'll have {overlap_pct}% skill coverage from earlier steps. "
                f"{'You still need to build ' + ' and '.join(top_gaps) + '.' if top_gaps else 'No skill gaps remaining — you are ready.'} "
                f"At ₹{salary} LPA, this is {round(salary/(node1_salary or 1)*100 - 100) if node1_salary and node1_salary > 0 else 'significantly'}% above your starting point."
            )
        else:
            desc = (
                f"Progression to {role_title}. "
                f"Building on your previous step, you'll be {overlap_pct}% aligned. "
                f"{'Focus next on: ' + ', '.join(top_gaps) + '.' if top_gaps else 'No additional skill gaps at this stage.'} "
                f"Salary grows to ₹{salary} LPA here."
            )

        node = {
            "node_id":             f"node_{i+2}",
            "role_title":          role_title,
            "node_order":          i + 2,
            "timeline_months":     cumulative_months,
            "required_skills":     required_skills,
            "skill_gap":           skill_gap[:5],
            "salary_estimate_lpa": salary,
            "risk_level":          risk_level,
            "description":         desc,
            "_seniority":          seniority,
        }
        nodes.append(node)
        # Update user_skills for next iteration (cumulative)
        user_skills = list(dict.fromkeys(user_skills + required_skills))

    # If graph gave us nothing useful, ensure at least 3 nodes
    if len(nodes) < 3:
        _fill_with_domain_anchors(nodes, target_domain, user_skills, cumulative_months, burnout)
        cumulative_months = nodes[-1]["timeline_months"] if nodes else 18

    # Strip internal fields
    for node in nodes:
        node.pop("_seniority", None)

    # ── Step 5: Edges ─────────────────────────────────────────────────────────
    edges = []
    for i in range(len(nodes) - 1):
        gap_preview = nodes[i+1].get("skill_gap", [])
        label = f"Build: {', '.join(gap_preview[:2])}" if gap_preview else "Upskill & apply"
        edges.append({
            "source": nodes[i]["node_id"],
            "target": nodes[i+1]["node_id"],
            "label":  label,
        })

    # ── Step 6: Neural probability ────────────────────────────────────────────
    probability = neural_probability(profile, domain_desc, prob_min, prob_max)

    # ── Step 7: Emotional forecast (rule-based from profile) ─────────────────
    emotional_forecast = _build_emotional_forecast(burnout, cumulative_months, target_domain)

    # ── Step 8: Alternative paths (neural, top-2 other domains) ──────────────
    alternative_paths = _build_alternative_paths(
        domain_scores, user_skills, profile, prob_min, prob_max
    )

    return {
        "current_role":          current_role or "Current Role",
        "target_role":           nodes[-1]["role_title"] if nodes else target_domain.title(),
        "success_probability":   probability,
        "total_transition_months": cumulative_months,
        "roadmap_nodes":         nodes,
        "roadmap_edges":         edges,
        "emotional_forecast":    emotional_forecast,
        "alternative_paths":     alternative_paths,
        "explanation":           "",  # Groq fills this
        "retrieved_doc_ids":     [d.get("doc_id", "") for d in retrieved_docs[:5]],
    }


def _fill_with_domain_anchors(
    nodes: list, domain: str, user_skills: list,
    start_months: int, burnout: int
):
    """Fallback: add generic seniority stages if graph gave sparse results."""
    from rag.knowledge_graph import build_career_graph
    G = build_career_graph()

    domain_nodes = sorted(
        [(n, d) for n, d in G.nodes(data=True) if d.get("domain") == domain],
        key=lambda x: x[1].get("seniority", 3)
    )
    existing_titles = {n["role_title"] for n in nodes}
    cumulative = start_months

    for role, data in domain_nodes[:3]:
        if role in existing_titles:
            continue
        required = data.get("skills", [])[:6]
        _, gap, ratio = semantic_skill_gap(user_skills, required, threshold=0.60)
        cumulative += 12
        nodes.append({
            "node_id":           f"node_{len(nodes)+1}",
            "role_title":        role,
            "node_order":        len(nodes) + 1,
            "timeline_months":   cumulative,
            "required_skills":   required,
            "skill_gap":         gap[:5],
            "salary_estimate_lpa": _get_salary(domain, data.get("seniority", 3)),
            "risk_level":        "High" if (1-ratio) > 0.65 else ("Medium" if (1-ratio) > 0.35 else "Low"),
            "description":       f"{role} in {domain}. Skill coverage: {round(ratio*100)}%.",
        })


def _build_emotional_forecast(burnout: int, total_months: int, domain: str) -> list[dict]:
    phases = []
    if burnout >= 7:
        phases.append({
            "phase":        "Recovery & Grounding",
            "timeline":     "Months 1–2",
            "stress_level": "High",
            "description":  "High burnout detected. Prioritise recovery first. Light learning (30 min/day). No applications yet.",
        })
        offset = 3
    else:
        offset = 1

    third = max(2, total_months // 3)
    phases += [
        {
            "phase":        "Skill Foundation",
            "timeline":     f"Months {offset}–{offset + third - 1}",
            "stress_level": "Medium",
            "description":  f"Core {domain} learning phase. Build fundamentals, ship first project. Stress is manageable with consistent routine.",
        },
        {
            "phase":        "Portfolio & Network",
            "timeline":     f"Months {offset + third}–{offset + third*2 - 1}",
            "stress_level": "Medium",
            "description":  "Apply skills to real projects. Attend meetups, contribute to open source. Imposter syndrome peaks here — normal.",
        },
        {
            "phase":        "Active Transition",
            "timeline":     f"Months {offset + third*2}–{total_months}",
            "stress_level": "High" if burnout >= 5 else "Medium",
            "description":  "Interview prep and applications. Intense but goal is in sight. Negotiate from a position of demonstrated skills.",
        },
    ]
    return phases


def _build_alternative_paths(
    domain_scores: list[tuple[str, float]],
    user_skills:   list[str],
    profile:       dict,
    prob_min:      int,
    prob_max:      int,
) -> list[dict]:
    """Build 2 alternative paths from second/third best domains (neural-ranked)."""
    G = build_career_graph()
    alts = []

    for domain, sim in domain_scores[1:3]:
        domain_nodes = sorted(
            [(n, d) for n, d in G.nodes(data=True) if d.get("domain") == domain],
            key=lambda x: x[1].get("seniority", 3)
        )
        if not domain_nodes:
            continue

        roles = [n for n, _ in domain_nodes[:3]]
        required_all = [s for _, d in domain_nodes[:2] for s in d.get("skills", [])]
        _, _, ratio  = semantic_skill_gap(user_skills, required_all[:8], threshold=0.60)

        raw_prob = int(prob_min + ratio * (prob_max - prob_min))
        alt_prob = max(prob_min, min(prob_max, raw_prob))

        alts.append({
            "path_name":          f"{domain.title()} Track",
            "roles":              roles,
            "total_months":       12 + round((1 - ratio) * 18),
            "success_probability": alt_prob,
        })

    return alts
